project:
  type: website
  output-dir: _site

website:
  title: "AntSciHub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Lab-notebooks/index.qmd
        text: Lab Notebooks
  sidebar:
    contents:
      - index.qmd
      - section: "Lab Notebooks"
        contents: lab-notebooks/*.qmd

format:
  html:
    theme: cosmo
    toc: true
