project:
  type: website
  output-dir: docs

website:
  title: "AntSciHub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Lab-notebooks/index.qmd
        text: Lab Notebooks

format:
  html:
    theme: cosmo
    toc: true
